### PR TITLE
Implemented Pagination

### PR DESCRIPTION
**Pull request by a9irudhh**
All posts in a page were looking odd, So implemented a quick Feature of pagination in Home Page, you can find the new Component created in Home Component

### CODE REVIEW

**Comment by Aaditya1978** [comment]
Hi @a9irudhh ,
Thanks for contributing to the project.
I check your changes, but I think at initial loading time, the page navigators are not sticking to bottom and also after loading , all the paginator are coming at once, can you please check once and try to fix it.

**Comment by a9irudhh** [comment]
Hey @Aaditya1978!,
Thank you for noticing. I have fixed it, can you check it again.

**Comment by Aaditya1978** [comment]
Hi @a9irudhh ,
I checked, but still after blogs are loaded all the paginators are coming at once, attached is the ss - 
image

**Comment by a9irudhh** [comment]
Ah!, I got it now. Fixed it ;)

**Comment by Aaditya1978** [comment]
Hi @a9irudhh ,
Thanks for your contribution, I am merging the code now.

**Pull request merged**
